### ISSUE TITLE
Is there a way to use NLU without server

### ISSUE THREAD

**Issue by redskate** [GeniSysAI/NLU#11]
Hi Adam

thank you for sharing this system. Is there a way to avoid using "Server" (since it is outdated and costs a lot of time to repair) ? I would just like to use the system as a chatbot without reverse engineering it totally.

Thanks in advance
Kind regards

**Comment by AdamMiltonBarker** [comment]
I would suggest using one of the new versions. https://github.com/LeukemiaAiResearch/GeniSysAI all of these systems are designed to be part of the networks but you can use them without if you remove the relevant iotJumpWay integration.

**Comment by redskate** [comment]
ok - thank you :)
I had a look at GeniSysAI - NLU seems there to be rather patched than updated. And there you do not provide any installation hints (which I guess could be taken from here)... In sum ... a kind of mess for me. I will "upgrade" myself to (try to) understand your interesting NLU approach (and yes reverse engineering...).

**Comment by AdamMiltonBarker** [comment]
> ok - thank you :)
> I had a look at GeniSysAI - NLU seems there to be rather patched than updated. And there you do not provide any installation hints (which I guess could be taken from here)... In sum ... a kind of mess for me. I will "upgrade" myself to (try to) understand your interesting NLU approach (and yes reverse engineering...).

Not sure what you are expecting, there is a new version of the TF1.14.0 (https://github.com/LeukemiaAiResearch/GeniSysAI/tree/master/NLU/RPI/RPI3/TF1.14.0)  which includes all the steps you need to install, And there is the new Tensorflow 2 version (https://github.com/LeukemiaAiResearch/GeniSysAI/tree/master/NLU/RPI/RPI3/TF2) which again, provides all of the steps to install successfully.  Both versions code cleaned up and improved and  updated to include in built text to speech, all you have to do is run the Setup.sh scripts to install.

Please feel free to not use the projects if you have issues as I won't be offering you any more help.

**Comment by AdamMiltonBarker** [comment]
> ok - thank you :)
> I had a look at GeniSysAI - NLU seems there to be rather patched than updated. And there you do not provide any installation hints (which I guess could be taken from here)... In sum ... a kind of mess for me. I will "upgrade" myself to (try to) understand your interesting NLU approach (and yes reverse engineering...).

Not sure what you are expecting, there is a new version of the TF1.14.0 project (this one) which includes all the steps you need to install:

https://github.com/LeukemiaAiResearch/GeniSysAI/tree/master/NLU/RPI/RPI3/TF1.14.0

And there is the new Tensorflow 2 version which again, provides all of the steps to install successfully.

https://github.com/LeukemiaAiResearch/GeniSysAI/tree/master/NLU/RPI/RPI3/TF2

Both versions code cleaned up and improved and updated to include in built text to speech, all you have to do is run the Setup.sh scripts to install.
